# Generated by Django 5.2.5 on 2025-08-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
